from flask import Flask, request, jsonify
from flask_cors import CORS
import pandas as pd
from database import (
    create_table, insert_expense, get_all_expenses,
    get_expenses_by_month, delete_expense, update_expense,
    set_budget, get_budgets
)
from insights import generate_insights
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.units import inch
from flask import send_file

app = Flask(__name__)
CORS(app)

create_table()

@app.route("/")
def home():
    return jsonify({"message": "Smart Expense Analyzer API is running"})

@app.route("/add-expense", methods=["POST"])
def add_expense():
    data = request.json
    insert_expense(data["date"], data["category"], data.get("description", ""), float(data["amount"]), data.get("payment_mode", ""))
    return jsonify({"message": "Expense added successfully"})

@app.route("/expenses", methods=["GET"])
def expenses():
    month = request.args.get("month")  # e.g. ?month=2026-05
    if month:
        return jsonify(get_expenses_by_month(month))
    return jsonify(get_all_expenses())

@app.route("/expenses/<int:expense_id>", methods=["DELETE"])
def delete(expense_id):
    delete_expense(expense_id)
    return jsonify({"message": "Expense deleted"})

@app.route("/expenses/<int:expense_id>", methods=["PUT"])
def update(expense_id):
    data = request.json
    update_expense(expense_id, data["date"], data["category"], data.get("description", ""), float(data["amount"]), data.get("payment_mode", ""))
    return jsonify({"message": "Expense updated"})

@app.route("/summary", methods=["GET"])
def summary():
    month = request.args.get("month")
    expense_list = get_expenses_by_month(month) if month else get_all_expenses()
    category_summary = {}
    for item in expense_list:
        cat = item["category"]
        category_summary[cat] = category_summary.get(cat, 0) + item["amount"]
    return jsonify([{"category": c, "amount": a} for c, a in category_summary.items()])

@app.route("/insights", methods=["GET"])
def insights():
    month = request.args.get("month")
    expense_list = get_expenses_by_month(month) if month else get_all_expenses()
    budgets = get_budgets()
    return jsonify(generate_insights(expense_list, budgets))

@app.route("/upload-csv", methods=["POST"])
def upload_csv():
    file = request.files["file"]
    df = pd.read_csv(file)
    required_columns = ["Date", "Category", "Description", "Amount", "Payment Mode"]
    for col in required_columns:
        if col not in df.columns:
            return jsonify({"error": f"Missing column: {col}"}), 400
    for _, row in df.iterrows():
        insert_expense(str(row["Date"]), str(row["Category"]), str(row["Description"]), float(row["Amount"]), str(row["Payment Mode"]))
    return jsonify({"message": f"CSV uploaded successfully. {len(df)} expenses imported."})

@app.route("/budgets", methods=["GET"])
def budgets_get():
    return jsonify(get_budgets())

@app.route("/budgets", methods=["POST"])
def budgets_set():
    data = request.json
    set_budget(data["category"], float(data["monthly_limit"]))
    return jsonify({"message": "Budget set successfully"})

@app.route("/export-pdf", methods=["GET"])
def export_pdf():
    month = request.args.get("month")
    expense_list = get_expenses_by_month(month) if month else get_all_expenses()
    budgets = get_budgets()
    insights_list = generate_insights(expense_list, budgets)

    total = sum(e["amount"] for e in expense_list)
    category_totals = {}
    for e in expense_list:
        category_totals[e["category"]] = category_totals.get(e["category"], 0) + e["amount"]

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=50, bottomMargin=40)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle('title', fontSize=22, fontName='Helvetica-Bold', textColor=colors.HexColor('#6c63ff'), spaceAfter=4)
    sub_style   = ParagraphStyle('sub',   fontSize=11, fontName='Helvetica',      textColor=colors.HexColor('#888888'), spaceAfter=20)
    head_style  = ParagraphStyle('head',  fontSize=13, fontName='Helvetica-Bold', textColor=colors.HexColor('#222222'), spaceBefore=16, spaceAfter=8)
    body_style  = ParagraphStyle('body',  fontSize=10, fontName='Helvetica',      textColor=colors.HexColor('#444444'), spaceAfter=4)

    label = f" — {month}" if month else " — All Time"
    story.append(Paragraph(f"Smart Expense Report{label}", title_style))
    story.append(Paragraph(f"Generated by ExpenseAI • Total: ₹{total:,.0f} • {len(expense_list)} transactions", sub_style))
    story.append(Spacer(1, 10))

    # Summary table
    story.append(Paragraph("Category Summary", head_style))
    sum_data = [["Category", "Amount (₹)", "% of Total"]]
    for cat, amt in sorted(category_totals.items(), key=lambda x: -x[1]):
        pct = (amt / total * 100) if total else 0
        sum_data.append([cat, f"₹{amt:,.0f}", f"{pct:.1f}%"])
    sum_data.append(["TOTAL", f"₹{total:,.0f}", "100%"])

    sum_table = Table(sum_data, colWidths=[2.2*inch, 1.8*inch, 1.5*inch])
    sum_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#6c63ff')),
        ('TEXTCOLOR',  (0,0), (-1,0), colors.white),
        ('FONTNAME',   (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',   (0,0), (-1,-1), 10),
        ('ROWBACKGROUNDS', (0,1), (-1,-2), [colors.HexColor('#f9f9ff'), colors.white]),
        ('BACKGROUND', (0,-1), (-1,-1), colors.HexColor('#eeeeee')),
        ('FONTNAME',   (0,-1), (-1,-1), 'Helvetica-Bold'),
        ('GRID',       (0,0),  (-1,-1), 0.5, colors.HexColor('#dddddd')),
        ('ALIGN',      (1,0),  (-1,-1), 'RIGHT'),
        ('PADDING',    (0,0),  (-1,-1), 7),
    ]))
    story.append(sum_table)
    story.append(Spacer(1, 16))

    # AI Insights
    story.append(Paragraph("AI Insights", head_style))
    for ins in insights_list:
        story.append(Paragraph(f"• {ins}", body_style))
    story.append(Spacer(1, 16))

    # Expense details
    story.append(Paragraph("Expense Details", head_style))
    exp_data = [["Date", "Category", "Description", "Amount", "Mode"]]
    for e in expense_list[:50]:  # limit to 50
        exp_data.append([e["date"], e["category"], e["description"] or "—", f"₹{e['amount']:,.0f}", e["payment_mode"] or "—"])

    exp_table = Table(exp_data, colWidths=[1.2*inch, 1.3*inch, 2.2*inch, 1.1*inch, 1*inch])
    exp_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#333333')),
        ('TEXTCOLOR',  (0,0), (-1,0), colors.white),
        ('FONTNAME',   (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE',   (0,0), (-1,-1), 9),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.HexColor('#fafafa'), colors.white]),
        ('GRID',       (0,0), (-1,-1), 0.4, colors.HexColor('#e0e0e0')),
        ('ALIGN',      (3,0), (3,-1), 'RIGHT'),
        ('PADDING',    (0,0), (-1,-1), 6),
    ]))
    story.append(exp_table)

    doc.build(story)
    buffer.seek(0)
    fname = f"expense_report_{month or 'all'}.pdf"
    return send_file(buffer, mimetype='application/pdf', as_attachment=True, download_name=fname)

if __name__ == "__main__":
    app.run(debug=True)
